name: Deploy Blazor App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish -c Release -o release --nologo

      - name: Prepare directory structure
        run: |
          mkdir -p publish/my-blazor-app
          cp -r release/wwwroot/* publish/my-blazor-app/
          cp publish/my-blazor-app/index.html publish/my-blazor-app/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish